{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rickbusarow.gradle-dependency-sync",
    "module": "gradle-dependency-sync-plugin",
    "version": "0.11.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "rejects": [
              "[2.+,2.17.1)"
            ]
          },
          "reason": "Cannot publish a plugin which resolves a vulnerable Log4j version (https://blog.gradle.org/log4j-vulnerability). Make sure to update your configuration so it does not happen."
        }
      ],
      "files": [
        {
          "name": "gradle-dependency-sync-plugin-0.11.5.jar",
          "url": "gradle-dependency-sync-plugin-0.11.5.jar",
          "size": 50157,
          "sha512": "53284f5e2e1c99813761ee6a1dbb7442d2b3303c7812ff2276dd2c93e685f9290197d4f04f9d641a0113d6fd86d1d0f94c01e74e8408be294034a5ce7c2975ba",
          "sha256": "180d99836d32560df8a553637331b0262150b1e0661ba059fcef7927628b0c5c",
          "sha1": "685615256dc785e6efdd98422c76228dc97783a0",
          "md5": "0a8452b9ce5fe4fbc2058a12837d6942"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "net.swiftzer.semver",
          "module": "semver",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "rejects": [
              "[2.+,2.17.1)"
            ]
          },
          "reason": "Cannot publish a plugin which resolves a vulnerable Log4j version (https://blog.gradle.org/log4j-vulnerability). Make sure to update your configuration so it does not happen."
        }
      ],
      "files": [
        {
          "name": "gradle-dependency-sync-plugin-0.11.5.jar",
          "url": "gradle-dependency-sync-plugin-0.11.5.jar",
          "size": 50157,
          "sha512": "53284f5e2e1c99813761ee6a1dbb7442d2b3303c7812ff2276dd2c93e685f9290197d4f04f9d641a0113d6fd86d1d0f94c01e74e8408be294034a5ce7c2975ba",
          "sha256": "180d99836d32560df8a553637331b0262150b1e0661ba059fcef7927628b0c5c",
          "sha1": "685615256dc785e6efdd98422c76228dc97783a0",
          "md5": "0a8452b9ce5fe4fbc2058a12837d6942"
        }
      ]
    }
  ]
}
